version: "2"
services:
  tf2:
    ports:
      - "27015:27015/udp"
  css:
    ports:
      - "27016:27015/udp"
  pz:
    ports:
      - "16261:16261"
      - "16261:16261/udp"
      - "16262-16286:16262-16286"